name: Build "turnip"






jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with: { ref: alpha }

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: turnip-23.2.0-T-Alpha_MrPurple.adpkg.zip
        path: turnip_workdir/turnip-23.2.0-T-Alpha_MrPurple.adpkg.zip
